---
- name: "Update/upgrade packages"
  become: true
  apt:
    update_cache: yes

- name: "Install nodejs, npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
