---
- name: "Create Directory"
  file:
    path: ~/app-directory
    state: directory

- name: "Unarchive files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/app-directory

- name: "Install Dependencies"
  shell: |
    cd ~/app-directory
    npm install

- name: "Executing node app with PM2"
  shell: |
    cd ~/app-directory/dist
    pm2 stop default
    # pm2 start npm --start
    pm2 start main.js
  register: execute_node
  
- name:
  debug:
    msg: "{{ execute_node.stdout_lines }}"
    
- name: "cpnfigure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
